# Generated by Django 4.2.3 on 2023-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_entity_fooditem_foodtype_producer_volunteer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
