# Generated by Django 4.2.3 on 2023-07-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_entity_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='id',
        ),
        migrations.AddField(
            model_name='producer',
            name='entity',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.entity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.entity'),
            preserve_default=False,
        ),
    ]
